#!/bin/bash

npm run production \
&& cd docs \
&& vuepress build . \
&& cd .. \
&& rm -rf dist/docs \
&& mv docs/.vuepress/dist dist/docs \
&& cd dist \
&& git add --all \
&& git commit -m "Build" \
&& git push \
&& cd ..
